# Unique project identifier in SonarQube
sonar.projectKey=cohort-9-mern-7911-abdul
sonar.projectName=cohort-9-mern-7911-abdul
sonar.projectVersion=1.0.0
sonar.host.url=http://localhost:9000
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info


# Path to the source directories
sonar.sources=backend/src,frontend/src

# Path to the test directories
sonar.tests=backend/src
sonar.test.inclusions=backend/src/**/*.spec.ts

# Files to exclude from analysis
sonar.exclusions=**/node_modules/**, **/dist/**, **/coverage/**, backend/package-lock.json, frontend/package-lock.json

# Source code encoding
sonar.sourceEncoding=UTF-8

# TSConfig files configuration for JavaScript/TypeScript analysis
sonar.typescript.tsconfigPaths=backend/tsconfig.json,frontend/tsconfig.json
